---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: readinessprobeexample:1.0.0
          resources:
            requests:
              memory: 200Mi
            limits:
              memory: 200Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz/ready
              port: 80
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 20
          ports:
            - containerPort: 80
              name: myapp
      imagePullSecrets:
        - name: tomato
